export interface MenuProduct {
  id: string
  name: string
  price: string
  numericPrice: number
  image: string
  description?: string
  tags?: string[]
  isTopSeller?: boolean
  isHighProtein?: boolean
  vegan?: boolean
  /** Package quantity label, e.g. "Pack of 2", "Box of 6", "Set of 6".
   *  Rendered on a second line below the product name.
   *  Only use for pack/box/set units — not for weight or size. */
  packageLabel?: string
  ingredients?: string[]
  allergens?: string[]
  storage?: string
}

export interface MenuProductWithCategory extends MenuProduct {
  category: string
  categorySlug: string
}

export interface MenuCategory {
  title: string
  slug: string
  subtitle?: string
  image: string
  products: MenuProduct[]
}

const menuProductCategories: MenuCategory[] = [
  {
    title: 'Signature Loaves (Pack of 10)',
    slug: 'signature-loaves',
    image: '/menu/curation_loaves.webp',
    products: [
      {
        id: 'authentic-thai-banana-loaf',
        name: 'Authentic Thai Banana Loaf',
        description: 'Moist, fragrant, and warmly spiced with cinnamon. Made with ripe Thai bananas for a naturally sweet, comforting crumb.',
        price: '฿ 190',
        numericPrice: 190,
        image: '/menu/authentic_banana_loaf_menu.webp',
        ingredients: ['Wheat Flour', 'Ripe Banana', 'Sugar', 'Refined Oil', 'Baking Soda', 'Baking Powder', 'Cinnamon', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten'],
        storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days. Best enjoyed at room temperature.',
      },
      {
        id: 'fresh-orange-loaf',
        name: 'Fresh Orange Loaf',
        description: 'Bright citrus notes in every slice. Made with freshly squeezed juice and real zest for a vibrant, uplifting flavour.',
        price: '฿ 220',
        numericPrice: 220,
        image: '/menu/fresh_orange_loaf.webp',
        ingredients: ['Wheat Flour', 'Fresh Orange Juice', 'Orange Zest', 'Sugar', 'Refined Oil', 'Baking Powder', 'Baking Soda', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten'],
        storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
      },
      {
        id: 'classical-carrot-cake',
        name: 'Classical Carrot Cake',
        description: 'A timeless recipe — fresh carrots, warm spice, and a perfectly tender crumb. Lightly sweetened and deeply satisfying.',
        price: '฿ 220',
        numericPrice: 220,
        image: '/menu/classical_carrot_cake_menu.webp',
        ingredients: ['Wheat Flour', 'Fresh Carrots', 'Sugar', 'Refined Oil', 'Baking Powder', 'Baking Soda', 'Cinnamon', 'Nutmeg', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten'],
        storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
      },
      {
        id: 'vanilla-butter-loaf-cake',
        name: 'Vanilla Butter Loaf Cake',
        description: 'Rich, golden, and buttery with a pure vanilla heart. Simple, elegant, and utterly comforting in every slice.',
        price: '฿ 250',
        numericPrice: 250,
        image: '/menu/premium_vanilla_cake_menu.webp',
        ingredients: ['Wheat Flour', 'Butter', 'Sugar', 'Milk', 'Baking Powder', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
      },
      {
        id: 'rich-chocolate-loaf',
        name: 'Rich Chocolate Loaf',
        description: 'Intensely chocolatey with layers of dark cocoa and melted chocolate. Dense, moist, and unapologetically indulgent.',
        price: '฿ 290',
        numericPrice: 290,
        image: '/menu/rich_chocolate_loaf_menu.webp',
        ingredients: ['Wheat Flour', 'Cocoa Powder', 'Dark Chocolate', 'Sugar', 'Refined Oil', 'Milk', 'Baking Powder', 'Baking Soda', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
      },
    ],
  },
  {
    title: 'Artisanal Brownies (Pack of 9)',
    slug: 'artisanal-brownies',
    image: '/menu/curation_brownies.webp',
    products: [
      {
        id: 'fudge-brownies',
        name: 'Fudge Brownies',
        description: 'Crinkle-topped, fudge-centred, and intensely chocolate. Each bite is rich, dense, and irresistibly gooey.',
        price: '฿ 270',
        numericPrice: 270,
        image: '/menu/fudge_brownies_menu.webp',
        isTopSeller: true,
        ingredients: ['Dark Chocolate', 'Butter', 'Sugar', 'Wheat Flour', 'Cocoa Powder', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store at room temperature for up to 3 days or refrigerate for up to 7 days.',
      },
      {
        id: 'mocha-brownies',
        name: 'Mocha Brownies',
        description: 'The depth of espresso meets bittersweet dark chocolate. Bold, aromatic, and perfectly balanced for coffee lovers.',
        price: '฿ 295',
        numericPrice: 295,
        image: '/menu/mocha_brownies_menu.webp',
        ingredients: ['Dark Chocolate', 'Butter', 'Sugar', 'Wheat Flour', 'Cocoa Powder', 'Instant Coffee', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store at room temperature for up to 3 days or refrigerate for up to 7 days.',
      },
      {
        id: 'nuts-biscoff-brownies',
        name: 'Nuts & Biscoff Brownies',
        description: 'Chocolate fudge brownies layered with Biscoff caramel spread and crunchy mixed nuts. Indulgent in every square.',
        price: '฿ 395',
        numericPrice: 395,
        image: '/menu/nuts_Biscoff_brownies_menu.webp',
        tags: ['Contains Nuts'],
        ingredients: ['Dark Chocolate', 'Butter', 'Sugar', 'Wheat Flour', 'Cocoa Powder', 'Biscoff Spread', 'Mixed Nuts (Cashews, Walnuts)', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Store at room temperature for up to 3 days or refrigerate for up to 7 days.',
      },
      {
        id: 'nutella-oreo-brownies',
        name: 'Nutella Oreo Brownies',
        description: 'Chewy chocolate brownies swirled with Nutella and studded with Oreo crumble. A playful, decadent treat.',
        price: '฿ 325',
        numericPrice: 325,
        image: '/menu/nutella_Oreo_brownies_menu.webp',
        ingredients: ['Dark Chocolate', 'Butter', 'Sugar', 'Wheat Flour', 'Cocoa Powder', 'Nutella', 'Oreo Cookies', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Store at room temperature for up to 3 days or refrigerate for up to 7 days.',
      },
    ],
  },
  {
    title: 'Tea Time Treats',
    slug: 'tea-time-treats',
    image: '/menu/curation_cookies.webp',
    products: [
      {
        id: 'classical-nankhatai',
        name: 'Classical Nankhatai',
        description: 'Traditional Indian shortbread crafted with ghee, cardamom, and premium flour. Delicate, crumbly, and lightly sweetened.',
        price: '฿ 195',
        numericPrice: 195,
        image: '/menu/classical_nankhatai_menu.webp',
        isTopSeller: true,
        ingredients: ['Wheat Flour', 'Gram Flour (Besan)', 'Semolina', 'Ghee', 'Powdered Sugar', 'Cardamom', 'Baking Powder'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store in an airtight container at room temperature for up to 10 days.',
      },
      {
        id: 'osmania-biscuits',
        name: 'Osmania Biscuits',
        description: "Hyderabad\u2019s beloved tea biscuit \u2014 mildly sweet, melt-in-the-mouth, and perfectly paired with a cup of chai.",
        price: '฿ 250',
        numericPrice: 250,
        image: '/menu/osmania_biscuits_menu.webp',
        ingredients: ['Wheat Flour', 'Butter', 'Sugar', 'Milk Powder', 'Baking Powder', 'Cardamom', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store in an airtight container at room temperature for up to 10 days.',
      },
      {
        id: 'almond-oats-choco-chip-cookies',
        name: 'Almond & Oats Choco Chip Cookies',
        description: 'Hearty, wholesome, and satisfying. Rolled oats, crunchy almonds, and dark chocolate chips in every bite.',
        price: '฿ 240',
        numericPrice: 240,
        image: '/menu/almond_oats_choco-chip_cookies_menu.webp',
        tags: ['Contains Nuts'],
        ingredients: ['Rolled Oats', 'Wheat Flour', 'Almonds', 'Dark Chocolate Chips', 'Butter', 'Brown Sugar', 'Vanilla Extract', 'Baking Soda', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Store in an airtight container at room temperature for up to 7 days.',
      },
      {
        id: 'double-choco-cookies',
        name: 'Double Choco Cookies',
        description: 'Two kinds of chocolate in every cookie — rich cocoa dough meets melty dark chocolate chips.',
        price: '฿ 250',
        numericPrice: 250,
        image: '/menu/double_choco_cookies_menu.webp',
        ingredients: ['Wheat Flour', 'Cocoa Powder', 'Dark Chocolate Chips', 'Butter', 'Sugar', 'Vanilla Extract', 'Baking Soda', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store in an airtight container at room temperature for up to 7 days.',
      },
      {
        id: 'coconut-cookies',
        name: 'Coconut Cookies',
        description: 'Crisp, golden cookies packed with toasted desiccated coconut. Light, aromatic, and irresistibly moreish.',
        price: '฿ 195',
        numericPrice: 195,
        image: '/menu/coconut_cookies_menu.webp',
        ingredients: ['Wheat Flour', 'Desiccated Coconut', 'Butter', 'Sugar', 'Vanilla Extract', 'Baking Powder', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store in an airtight container at room temperature for up to 10 days.',
      },
      {
        id: 'gluten-free-nuts-cookies',
        name: 'Gluten Free Nuts Cookies - 225gms',
        description: 'A high-protein, gluten-free treat made with almond flour and a medley of premium nuts. Nutritious never tasted this good.',
        price: '฿ 299',
        numericPrice: 299,
        image: '/menu/Gluten_free_nuts_cookies.webp',
        tags: ['Gluten Free', 'Ekadashi Special'],
        isTopSeller: true,
        isHighProtein: true,
        ingredients: ['Almond Flour', 'Mixed Nuts (Cashews, Almonds, Pistachios)', 'Coconut Sugar', 'Refined Oil', 'Vanilla Extract', 'Baking Soda', 'Salt'],
        allergens: ['Nuts'],
        storage: 'Store in an airtight container at room temperature for up to 10 days.',
      },
      {
        id: 'assorted-biscoff-truffles-pack-of-12',
        name: 'Assorted Biscoff Truffles (12 pcs)',
        description: 'Hand-rolled truffles in dark and white chocolate, each with a luscious Biscoff cream centre. Twelve little luxuries.',
        price: '฿ 400',
        numericPrice: 400,
        image: '/menu/assorted_biscoff_truffles.webp',
        ingredients: ['Biscoff Cookies', 'Cream Cheese', 'Dark Chocolate', 'White Chocolate', 'Biscoff Spread', 'Cocoa Powder'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 5 days.',
      },
      {
        id: 'cinnamon-rolls-set-of-6',
        name: 'Cinnamon Rolls',
        packageLabel: 'Set of 6',
        description: 'Soft, pillowy rolls swirled with warm cinnamon sugar. Baked fresh to order and best enjoyed slightly warm.',
        price: '฿ 190',
        numericPrice: 190,
        image: '/menu/cinnamon_rolls_menu.webp',
        ingredients: ['Wheat Flour', 'Butter', 'Sugar', 'Milk', 'Cinnamon', 'Baking Powder', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Best consumed within 2 days. Reheat for 20 seconds before serving.',
      },
      {
        id: 'blueberry-muffins',
        name: 'Blueberry Muffins',
        packageLabel: 'Pack of 2',
        description: 'Soft, fluffy muffins bursting with juicy blueberries.',
        price: '฿ 110',
        numericPrice: 110,
        image: '/menu/blueberyy_muffins_menu.webp',
        ingredients: ['Wheat Flour', 'Fresh Blueberries', 'Butter', 'Sugar', 'Milk', 'Baking Powder', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Best consumed fresh. Refrigerate and reheat within 2 days.',
      },
      {
        id: 'chocolate-muffins',
        name: 'Chocolate Muffins',
        packageLabel: 'Pack of 2',
        description: 'Rich chocolate muffins with a soft and moist crumb.',
        price: '฿ 110',
        numericPrice: 110,
        image: '/menu/choclate_muffins_menu.webp',
        ingredients: ['Wheat Flour', 'Cocoa Powder', 'Dark Chocolate Chips', 'Butter', 'Sugar', 'Milk', 'Baking Powder', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Best consumed fresh. Refrigerate and reheat within 2 days.',
      },
    ],
  },
  {
    title: 'Premium Cakes',
    slug: 'premium-cakes',
    image: '/menu/premium_blueberry_cheese_cake_menu.webp',
    products: [
      {
        id: 'red-velvet-cake',
        name: 'Red Velvet Cake',
        description: 'Velvety cocoa sponge with a signature crimson crumb, finished with silky cream cheese frosting. A timeless classic.',
        price: '฿ 590 / lb',
        numericPrice: 590,
        image: '/menu/red_velvet_cake.webp',
        ingredients: ['Wheat Flour', 'Cocoa Powder', 'Butter', 'Sugar', 'Milk', 'Red Food Colour', 'Baking Soda', 'White Vinegar', 'Vanilla Extract', 'Cream Cheese Frosting', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'premium-biscoff-cheese-cake',
        name: 'Premium Biscoff Cheese Cake',
        description: 'Dreamy no-bake cheesecake on a Biscoff cookie base, crowned with caramelised spread. Showstopping and sublime.',
        price: '฿ 690 / lb',
        numericPrice: 690,
        image: '/menu/biscoff_cheese_cake_menu.webp',
        ingredients: ['Biscoff Cookies', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Biscoff Spread', 'Butter', 'Gelatin-Free Setting Agent', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'premium-blueberry-cheese-cake',
        name: 'Premium Blueberry Cheese Cake',
        description: 'Creamy cheesecake on a buttery biscuit base, topped with a vivid blueberry compote. Fresh, tangy, and luxurious.',
        price: '฿ 690 / lb',
        numericPrice: 690,
        image: '/menu/premium_blueberry_cheese_cake_menu.webp',
        ingredients: ['Digestive Biscuits', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Fresh Blueberries', 'Blueberry Compote', 'Butter', 'Gelatin-Free Setting Agent', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'premium-strawberry-cheese-cake',
        name: 'Premium Strawberry Cheese Cake',
        description: 'Velvety cheesecake adorned with a bright strawberry compote. Delicate, fruity, and elegantly indulgent.',
        price: '฿ 690 / lb',
        numericPrice: 690,
        image: '/menu/premium_strawberry_cheese_cake_menu.webp',
        ingredients: ['Digestive Biscuits', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Fresh Strawberries', 'Strawberry Compote', 'Butter', 'Gelatin-Free Setting Agent', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'seasonal-mango-cheese-cake',
        name: 'Seasonal Mango Cheese Cake',
        description: 'Alphonso mango pulp folded into a light creamy cheesecake. A seasonal celebration of India’s finest fruit.',
        price: '฿ 690 / lb',
        numericPrice: 690,
        image: '/menu/Seasonal_mango_cheese_cake_menu.webp',
        ingredients: ['Digestive Biscuits', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Alphonso Mango Pulp', 'Fresh Mango', 'Butter', 'Gelatin-Free Setting Agent', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'traditional-mawa-cake',
        name: 'Traditional Mawa Cake',
        description: 'A Mumbai-style heirloom cake enriched with mawa, cardamom, and saffron. Dense, aromatic, and deeply nostalgic.',
        price: '฿ 390 / lb',
        numericPrice: 390,
        image: '/menu/traditional_mawa_menu.webp',
        isTopSeller: true,
        ingredients: ['Wheat Flour', 'Mawa (Khoya)', 'Butter', 'Sugar', 'Milk', 'Cardamom', 'Saffron', 'Baking Powder', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 4 days.',
      },
      {
        id: 'date-and-walnut-cake-no-sugar',
        name: 'Date and Walnut Cake (No sugar)',
        description: 'Naturally sweetened by Medjool dates and enriched with walnuts. A guilt-free, high-protein indulgence with no added sugar.',
        price: '฿ 390 / lb',
        numericPrice: 390,
        image: '/menu/Date_Walnut_Cake_menu.webp',
        tags: ['No Sugar', 'Contains Nuts'],
        isHighProtein: true,
        isTopSeller: true,
        ingredients: ['Wheat Flour', 'Medjool Dates', 'Walnuts', 'Refined Oil', 'Milk', 'Baking Soda', 'Baking Powder', 'Cinnamon', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Keep refrigerated. Best consumed within 4 days.',
      },
      {
        id: 'rose-n-pistachio-cake',
        name: 'Rose n Pistachio Cake',
        description: 'Fragrant rose water and premium pistachios in every slice. A floral, nutty cake inspired by Persian confectionery.',
        price: '฿ 590 / lb',
        numericPrice: 590,
        image: '/menu/Rose_pistacho_cake_menu.webp',
        tags: ['Contains Nuts'],
        isTopSeller: true,
        ingredients: ['Wheat Flour', 'Pistachios', 'Rose Water', 'Rose Essence', 'Butter', 'Sugar', 'Milk', 'Baking Powder', 'Cardamom', 'Vanilla Extract', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Keep refrigerated. Best consumed within 4 days.',
      },
      {
        id: 'gluten-free-nuts-cake-ekadashi',
        name: 'Gluten free Nuts cake',
        description: 'Almond flour, coconut milk, and a medley of premium nuts — a high-protein, gluten-free cake that tastes anything but virtuous.',
        price: '฿ 590 / lb',
        numericPrice: 590,
        image: '/menu/Ekadashi_Nuts_Cake.webp',
        tags: ['Gluten Free', 'Ekadashi Special'],
        isHighProtein: true,
        isTopSeller: true,
        ingredients: ['Almond Flour', 'Mixed Nuts (Cashews, Almonds, Walnuts, Pistachios)', 'Coconut Sugar', 'Refined Oil', 'Coconut Milk', 'Baking Powder', 'Cardamom', 'Vanilla Extract', 'Salt'],
        allergens: ['Nuts'],
        storage: 'Keep refrigerated. Best consumed within 4 days.',
      },
    ],
  },
  {
    title: 'Savory Bites',
    slug: 'savory-bites',
    image: '/menu/curation_savory.webp',
    products: [
      {
        id: 'pizza-muffins-box-of-6',
        name: 'Pizza Muffins',
        packageLabel: 'Box of 6',
        description: 'Cheesy, herb-flecked, and golden-baked. Mini muffins inspired by classic pizza flavours — a perfect savoury snack.',
        price: '฿ 195',
        numericPrice: 195,
        image: '/menu/pizza_muffins_menu.webp',
        isTopSeller: true,
        ingredients: ['Wheat Flour', 'Tomato Sauce', 'Mozzarella Cheese', 'Bell Peppers', 'Olives', 'Mixed Herbs', 'Olive Oil', 'Baking Powder', 'Salt'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Best consumed fresh. Refrigerate and reheat within 2 days.',
      },
      {
        id: 'spinach-muffins-box-of-6',
        name: 'Spinach Muffins',
        packageLabel: 'Box of 6',
        description: 'Wholesome spinach and feta baked into soft, fragrant muffins. Light, flavourful, and satisfying.',
        price: '฿ 195',
        numericPrice: 195,
        image: '/menu/spinach_muffins_menu.webp',
        ingredients: ['Wheat Flour', 'Fresh Spinach', 'Feta Cheese', 'Butter', 'Milk', 'Baking Powder', 'Garlic', 'Mixed Herbs', 'Salt', 'Pepper'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Best consumed fresh. Refrigerate and reheat within 2 days.',
      },
      {
        id: 'cheesy-cashews',
        name: 'Cheesy Cashews (125g)',
        description: 'Slow-roasted cashews dusted with cheddar seasoning. A dangerously addictive snack for every occasion.',
        price: '฿ 240',
        numericPrice: 240,
        image: '/menu/cheesy_cashews_menu.webp',
        tags: ['Contains Nuts'],
        ingredients: ['Cashews', 'Cheddar Cheese Powder', 'Rice Flour', 'Salt', 'Mixed Spices', 'Refined Oil'],
        allergens: ['Dairy', 'Nuts'],
        storage: 'Store in an airtight container at room temperature for up to 14 days.',
      },
      {
        id: '7-seed-mukhwas',
        name: '7 Seed Mukhwas (125g)',
        description: 'A vibrant blend of seven seeds — aromatic, crunchy, and traditionally enjoyed as a digestive after meals.',
        price: '฿ 160',
        numericPrice: 160,
        image: '/menu/7_seed_mukhwas_menu.webp',
        ingredients: ['Fennel Seeds', 'Sesame Seeds', 'Flax Seeds', 'Pumpkin Seeds', 'Sunflower Seeds', 'Melon Seeds', 'Coriander Seeds', 'Sugar Coating', 'Natural Colours'],
        allergens: [],
        storage: 'Store in an airtight container at room temperature for up to 30 days.',
      },
      {
        id: 'cheese-straws',
        name: 'Cheese Straws',
        packageLabel: 'Pack of 12',
        description: 'Buttery, flaky, and rich with aged cheddar. An elegant savoury snack that pairs beautifully with tea or drinks.',
        price: '฿ 210',
        numericPrice: 210,
        image: '/menu/cheese_straws_menu.webp',
        ingredients: ['Wheat Flour', 'Cheddar Cheese', 'Butter', 'Salt', 'Paprika', 'Cayenne Pepper', 'Mustard Powder'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store in an airtight container at room temperature for up to 7 days.',
      },
    ],
  },
  {
    title: 'Middle Eastern',
    slug: 'middle-eastern',
    image: '/menu/curation_middleeastern.webp',
    products: [
      {
        id: 'kunafa-dates-pack-of-6',
        name: 'Kunafa Dates',
        packageLabel: 'Pack of 6',
        description: 'Crispy kataifi pastry filled with creamy cheese and sweet Medjool dates, finished with rose and orange blossom syrup.',
        price: '฿ 300',
        numericPrice: 300,
        image: '/menu/kunafa_dates_menu.webp',
        isTopSeller: true,
        ingredients: ['Kataifi Pastry (Wheat)', 'Medjool Dates', 'Cream Cheese', 'Sugar Syrup', 'Rose Water', 'Clarified Butter (Ghee)', 'Pistachios', 'Orange Blossom Water'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Best enjoyed warm. Refrigerate and reheat within 3 days.',
      },
      {
        id: 'baklava',
        name: 'Baklava',
        description: 'Layers of golden phyllo pastry, premium mixed nuts, and fragrant rose water syrup. A Middle Eastern icon.',
        price: '฿ 590 / lb',
        numericPrice: 590,
        image: '/menu/baklava_menu.webp',
        tags: ['Contains Nuts'],
        ingredients: ['Phyllo Pastry (Wheat)', 'Mixed Nuts (Walnuts, Pistachios, Cashews)', 'Clarified Butter (Ghee)', 'Sugar Syrup', 'Rose Water', 'Cardamom', 'Cinnamon'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Store at room temperature for up to 7 days or refrigerate for up to 14 days.',
      },
      {
        id: 'basbousa',
        name: 'Basbousa',
        description: 'Tender semolina cake soaked in rose water syrup. Warmly spiced and wonderfully satisfying.',
        price: '฿ 550 / lb',
        numericPrice: 550,
        image: '/menu/basbousa_menu.webp',
        ingredients: ['Semolina', 'Sugar', 'Coconut', 'Clarified Butter (Ghee)', 'Yogurt', 'Baking Powder', 'Sugar Syrup', 'Rose Water'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Store at room temperature for up to 5 days or refrigerate for up to 10 days.',
      },
      {
        id: 'dubai-chocolates',
        name: 'Dubai Chocolate Bar',
        description: 'Dark chocolate housing crispy kataifi and rich pistachio cream. The iconic Dubai treat — indulgence redefined.',
        price: '฿ 690',
        numericPrice: 690,
        image: '/menu/kunafa_dubai_chocolate_bars.webp',
        ingredients: ['Dark Chocolate', 'Kataifi Pastry (Wheat)', 'Pistachio Cream', 'Tahini', 'Clarified Butter (Ghee)', 'Pistachios', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Keep refrigerated. Best consumed within 7 days.',
      },
      {
        id: 'dubai-chocolate-mini-bar',
        name: 'Mini Dubai Chocolate Bar',
        description: 'All the luxury of the iconic Dubai chocolate bar in a perfectly portioned single serving.',
        price: '฿ 399',
        numericPrice: 399,
        image: '/menu/dubai_chocolate_mini_bar_menu.webp',
        ingredients: ['Dark Chocolate', 'Kataifi Pastry (Wheat)', 'Pistachio Cream', 'Tahini', 'Clarified Butter (Ghee)', 'Pistachios', 'Salt'],
        allergens: ['Gluten', 'Dairy', 'Nuts'],
        storage: 'Keep refrigerated. Best consumed within 7 days.',
      },
    ],
  },
  {
    title: 'Crumble Tubs (Pack of 2 - 250g)',
    slug: 'crumble-tubs',
    image: '/menu/biscoff_crumble cake_menu.webp',
    products: [
      {
        id: 'biscoff-creamcheese-crumble-tub',
        name: 'Biscoff Creamcheese',
        packageLabel: 'Pack of 2',
        description: 'Cookie crumble, velvety cream cheese mousse, and a caramelised Biscoff drizzle — layered to perfection.',
        price: '฿ 250',
        numericPrice: 250,
        image: '/menu/biscoff_crumble cake_menu.webp',
        ingredients: ['Biscoff Cookies', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Biscoff Spread', 'Butter', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'blueberry-creamcheese-crumble-tub',
        name: 'Blueberry Creamcheese',
        packageLabel: 'Pack of 2',
        description: 'Buttery biscuit crumble, light cream cheese mousse, and a vibrant blueberry compote. Fresh and indulgent.',
        price: '฿ 195',
        numericPrice: 195,
        image: '/menu/blueberry_cheesecake_crumble_menu.webp',
        ingredients: ['Digestive Biscuits', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Fresh Blueberries', 'Blueberry Compote', 'Butter', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'mango-crumble-tub',
        name: 'Mango',
        packageLabel: 'Pack of 2',
        description: 'Cream cheese mousse layered with fresh mango pulp and golden biscuit crumble. Tropical perfection in a tub.',
        price: '฿ 180',
        numericPrice: 180,
        image: '/menu/mango_crumblecake_menu (1).webp',
        ingredients: ['Digestive Biscuits', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Mango Pulp', 'Fresh Mango', 'Butter', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'tiramisu-crumble-tub',
        name: 'Tiramisu',
        packageLabel: 'Pack of 2',
        description: 'Coffee-soaked savoiardi, rich mascarpone cream, and a fine cocoa dusting. A classic reinvented in a tub.',
        price: '฿ 350',
        numericPrice: 350,
        image: '/menu/tiramisu_crumblecake_menu.webp',
        ingredients: ['Savoiardi Biscuits (Wheat)', 'Mascarpone Cheese', 'Whipping Cream', 'Sugar', 'Strong Coffee', 'Cocoa Powder', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'chocolate-crumble-tub',
        name: 'Chocolate',
        packageLabel: 'Pack of 2',
        description: 'Dark chocolate cream cheese, Oreo crumble, and a cocoa finish. Deeply indulgent and simply divine.',
        price: '฿ 180',
        numericPrice: 180,
        image: '/menu/chocolate_crumblecake_menu (1).webp',
        ingredients: ['Oreo Cookies', 'Cream Cheese', 'Whipping Cream', 'Dark Chocolate', 'Cocoa Powder', 'Sugar', 'Butter', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
      {
        id: 'strawberry-crumble-tub',
        name: 'Strawberry',
        packageLabel: 'Pack of 2',
        description: 'Fresh strawberry compote, cream cheese mousse, and a buttery biscuit base. Fruity, fresh, and divine.',
        price: '฿ 195',
        numericPrice: 195,
        image: '/menu/strawberry_crumblecake_menu (1).webp',
        ingredients: ['Digestive Biscuits', 'Cream Cheese', 'Whipping Cream', 'Sugar', 'Fresh Strawberries', 'Strawberry Compote', 'Butter', 'Vanilla Extract'],
        allergens: ['Gluten', 'Dairy'],
        storage: 'Keep refrigerated. Best consumed within 3 days.',
      },
    ],
  },
  {
    title: 'Vegan',
    slug: 'vegan',
    image: '/menu/Date_Walnut_Cake_menu.webp',
    products: (() => {
      // Duplicate all Signature Loaves + Premium Cakes (excluding Traditional Mawa Cake)
      // with +50 THB on every item
      const signatureLoaves: MenuProduct[] = [
        {
          id: 'vegan-authentic-thai-banana-loaf',
          name: 'Authentic Thai Banana Loaf (Vegan)',
          description: 'Moist, fragrant, and warmly spiced with cinnamon. Made with ripe Thai bananas and plant-based ingredients.',
          price: '฿ 250',
          numericPrice: 250,
          image: '/menu/authentic_banana_loaf_menu.webp',
          vegan: true,
          ingredients: ['Wheat Flour', 'Ripe Banana', 'Coconut Sugar', 'Coconut Oil', 'Plant-Based Milk', 'Baking Soda', 'Baking Powder', 'Cinnamon', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten'],
          storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
        },
        {
          id: 'vegan-fresh-orange-loaf',
          name: 'Fresh Orange Loaf',
          description: 'Bright citrus notes in every slice, made with freshly squeezed orange juice. A vibrant, uplifting plant-based loaf.',
          price: '฿ 270',
          numericPrice: 270,
          image: '/menu/fresh_orange_loaf.webp',
          vegan: true,
          ingredients: ['Wheat Flour', 'Fresh Orange Juice', 'Orange Zest', 'Coconut Sugar', 'Coconut Oil', 'Baking Powder', 'Baking Soda', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten'],
          storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
        },
        {
          id: 'vegan-classical-carrot-cake',
          name: 'Classical Carrot Cake',
          description: 'A timeless recipe — fresh carrots, warm spice, and a tender crumb. Made entirely with plant-based ingredients.',
          price: '฿ 270',
          numericPrice: 270,
          image: '/menu/classical_carrot_cake_menu.webp',
          vegan: true,
          ingredients: ['Wheat Flour', 'Fresh Carrots', 'Coconut Sugar', 'Coconut Oil', 'Baking Powder', 'Baking Soda', 'Cinnamon', 'Nutmeg', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten'],
          storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
        },
        {
          id: 'vegan-vanilla-butter-loaf-cake',
          name: 'Vanilla Butter Loaf Cake',
          description: 'Rich, golden, and buttery with a pure vanilla heart. All the luxury of the original, made entirely vegan.',
          price: '฿ 300',
          numericPrice: 300,
          image: '/menu/premium_vanilla_cake_menu.webp',
          vegan: true,
          ingredients: ['Wheat Flour', 'Vegan Butter', 'Coconut Sugar', 'Oat Milk', 'Baking Powder', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten'],
          storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
        },
        {
          id: 'vegan-rich-chocolate-loaf',
          name: 'Rich Chocolate Loaf',
          description: 'Intensely chocolatey with dark cocoa and dairy-free chocolate. Dense, moist, and unapologetically indulgent.',
          price: '฿ 350',
          numericPrice: 350,
          image: '/menu/rich_chocolate_loaf_menu.webp',
          vegan: true,
          ingredients: ['Wheat Flour', 'Cocoa Powder', 'Dark Chocolate (Dairy-Free)', 'Coconut Sugar', 'Coconut Oil', 'Oat Milk', 'Baking Powder', 'Baking Soda', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten'],
          storage: 'Store at room temperature for up to 2 days or refrigerate for up to 5 days.',
        },
      ]
      const premiumCakes: MenuProduct[] = [
        {
          id: 'vegan-red-velvet-cake',
          name: 'Red Velvet Cake',
          description: 'Velvety cocoa sponge with a signature crimson crumb and vegan cream cheese frosting. A timeless classic, plant-based.',
          price: '฿ 650 / lb',
          numericPrice: 650,
          image: '/menu/red_velvet_cake.webp',
          vegan: true,
          ingredients: ['Wheat Flour', 'Cocoa Powder', 'Vegan Butter', 'Coconut Sugar', 'Oat Milk', 'Red Beet Juice', 'Baking Soda', 'Apple Cider Vinegar', 'Vanilla Extract', 'Vegan Cream Cheese Frosting', 'Salt'],
          allergens: ['Gluten'],
          storage: 'Keep refrigerated. Best consumed within 3 days.',
        },
        {
          id: 'vegan-premium-biscoff-cheese-cake',
          name: 'Premium Biscoff Cheese Cake (Vegan)',
          description: 'Dreamy no-bake vegan cheesecake on a Biscoff cookie base, crowned with caramelised spread. Showstopping and plant-based.',
          price: '฿ 750 / lb',
          numericPrice: 750,
          image: '/menu/biscoff_cheese_cake_menu.webp',
          vegan: true,
          ingredients: ['Biscoff Cookies', 'Vegan Cream Cheese', 'Coconut Cream', 'Coconut Sugar', 'Biscoff Spread', 'Vegan Butter', 'Agar Agar', 'Vanilla Extract'],
          allergens: ['Gluten'],
          storage: 'Keep refrigerated. Best consumed within 3 days.',
        },
        {
          id: 'vegan-premium-blueberry-cheese-cake',
          name: 'Premium Blueberry Cheese Cake',
          description: 'Creamy vegan cheesecake on a buttery biscuit base, topped with a vivid blueberry compote. Fresh and plant-based.',
          price: '฿ 750 / lb',
          numericPrice: 750,
          image: '/menu/premium_blueberry_cheese_cake_menu.webp',
          vegan: true,
          ingredients: ['Digestive Biscuits (Vegan)', 'Vegan Cream Cheese', 'Coconut Cream', 'Coconut Sugar', 'Fresh Blueberries', 'Blueberry Compote', 'Vegan Butter', 'Agar Agar', 'Vanilla Extract'],
          allergens: ['Gluten'],
          storage: 'Keep refrigerated. Best consumed within 3 days.',
        },
        {
          id: 'vegan-premium-strawberry-cheese-cake',
          name: 'Premium Strawberry Cheese Cake',
          description: 'Velvety vegan cheesecake adorned with a bright strawberry compote. Delicate, fruity, and elegantly plant-based.',
          price: '฿ 750 / lb',
          numericPrice: 750,
          image: '/menu/premium_strawberry_cheese_cake_menu.webp',
          vegan: true,
          ingredients: ['Digestive Biscuits (Vegan)', 'Vegan Cream Cheese', 'Coconut Cream', 'Coconut Sugar', 'Fresh Strawberries', 'Strawberry Compote', 'Vegan Butter', 'Agar Agar', 'Vanilla Extract'],
          allergens: ['Gluten'],
          storage: 'Keep refrigerated. Best consumed within 3 days.',
        },
        {
          id: 'vegan-seasonal-mango-cheese-cake',
          name: 'Seasonal Mango Cheese Cake',
          description: 'Alphonso mango pulp folded into a light vegan cheesecake. A seasonal celebration of India’s finest fruit.',
          price: '฿ 750 / lb',
          numericPrice: 750,
          image: '/menu/Seasonal_mango_cheese_cake_menu.webp',
          vegan: true,
          ingredients: ['Digestive Biscuits (Vegan)', 'Vegan Cream Cheese', 'Coconut Cream', 'Coconut Sugar', 'Alphonso Mango Pulp', 'Fresh Mango', 'Vegan Butter', 'Agar Agar', 'Vanilla Extract'],
          allergens: ['Gluten'],
          storage: 'Keep refrigerated. Best consumed within 3 days.',
        },
        // Traditional Mawa Cake excluded from Vegan
        {
          id: 'vegan-date-and-walnut-cake',
          name: 'Date and Walnut Cake (No sugar)',
          description: 'Naturally sweetened by Medjool dates and enriched with walnuts. A guilt-free, high-protein, fully vegan indulgence.',
          price: '฿ 450 / lb',
          numericPrice: 450,
          image: '/menu/Date_Walnut_Cake_menu.webp',
          tags: ['No Sugar', 'Contains Nuts'],
          isHighProtein: true,
          vegan: true,
          ingredients: ['Wheat Flour', 'Medjool Dates', 'Walnuts', 'Coconut Oil', 'Oat Milk', 'Baking Soda', 'Baking Powder', 'Cinnamon', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten', 'Nuts'],
          storage: 'Keep refrigerated. Best consumed within 4 days.',
        },
        {
          id: 'vegan-rose-n-pistachio-cake',
          name: 'Rose n Pistachio Cake',
          description: 'Fragrant rose water and premium pistachios in every slice. A floral, nutty, Persian-inspired cake made entirely vegan.',
          price: '฿ 650 / lb',
          numericPrice: 650,
          image: '/menu/Rose_pistacho_cake_menu.webp',
          tags: ['Contains Nuts'],
          vegan: true,
          ingredients: ['Wheat Flour', 'Pistachios', 'Rose Water', 'Rose Essence', 'Vegan Butter', 'Coconut Sugar', 'Oat Milk', 'Baking Powder', 'Cardamom', 'Vanilla Extract', 'Salt'],
          allergens: ['Gluten', 'Nuts'],
          storage: 'Keep refrigerated. Best consumed within 4 days.',
        },
        {
          id: 'vegan-gluten-free-nuts-cake',
          name: 'Gluten-Free Nuts Cake',
          description: 'Almond flour, coconut milk, and a medley of premium nuts — a high-protein, gluten-free, fully vegan cake.',
          price: '฿ 650 / lb',
          numericPrice: 650,
          image: '/menu/gluten_free_nuts_cake_menu.webp',
          tags: ['High Protein', 'Vegan', 'Ekadashi Special', 'Calories Free'],
          isHighProtein: true,
          vegan: true,
          ingredients: ['Almond Flour', 'Mixed Nuts (Cashews, Almonds, Walnuts, Pistachios)', 'Coconut Sugar', 'Coconut Oil', 'Coconut Milk', 'Baking Powder', 'Cardamom', 'Vanilla Extract', 'Salt'],
          allergens: ['Nuts'],
          storage: 'Keep refrigerated. Best consumed within 4 days.',
        },
      ]
      return [...signatureLoaves, ...premiumCakes]
    })(),
  },
]

const withCategory = (
  category: MenuCategory,
  product: MenuProduct,
): MenuProductWithCategory => ({
  ...product,
  category: category.title,
  categorySlug: category.slug,
})

export const menuProducts = menuProductCategories.flatMap((category) =>
  category.products.map((product) => withCategory(category, product)),
)

const TOP_SELLER_ORDER = [
  'kunafa-dates-pack-of-6',
  'rose-n-pistachio-cake',
  'gluten-free-nuts-cake-ekadashi',
  'date-and-walnut-cake-no-sugar',
]

export const topSellerProducts = menuProducts
  .filter((product) => product.isTopSeller)
  .sort((a, b) => {
    const ai = TOP_SELLER_ORDER.indexOf(a.id)
    const bi = TOP_SELLER_ORDER.indexOf(b.id)
    const aRank = ai === -1 ? TOP_SELLER_ORDER.length : ai
    const bRank = bi === -1 ? TOP_SELLER_ORDER.length : bi
    return aRank - bRank
  })

export const menuCategories: MenuCategory[] = [
  {
    title: 'Top Seller',
    slug: 'top-seller',
    image: '/menu/classical_nankhatai_menu.webp',
    products: topSellerProducts,
  },
  ...menuProductCategories,
]

export const menuCategoryOptions = [
  'All',
  ...menuCategories.map((category) => category.title),
]

export function getMenuProductsForCategory(categoryTitle: string) {
  if (categoryTitle === 'All') {
    return menuProducts
  }

  const category = menuCategories.find(
    (menuCategory) => menuCategory.title === categoryTitle,
  )

  return category
    ? category.products.map((product) => withCategory(category, product))
    : []
}
